### ISSUE TITLE
Messages: Investigate and describe server code 160

### ISSUE THREAD

**Issue by JurgenR** [JurgenR/aioslsk#180]
Unknown code 160 is being sent by the server. It appears to contain a list with 1 string : "bryan adams" . This search term seems to be blocked (similarly to "adele")

**Comment by JurgenR** [comment]
This is used to block search results on the client side in case that the search term in not directly searched for. The server would block any searches that match that string, however if the title of one the artists songs is searched the filter could be circumvented.

It's still unclear how far this filtering goes: is it case sensitive, can the words be in any order etc. Why is there currently only 1 in the list?

**Comment by mathiascode** [comment]
> It's still unclear how far this filtering goes: is it case sensitive, can the words be in any order etc. Why is there currently only 1 in the list?

Some quick testing with different file name variations seems to suggest that SlskQt checks if a file path contains an exact banned phrase (case-insensitive). Essentially if banned_phrase in file_path.lower().

**Comment by mathiascode** [comment]
Any ideas for what to name the message? I was thinking something like ExcludedSearchPhrases.

**Comment by jpdillingham** [comment]
Given the recent 'bryan adams' news I'm wondering if this is used to filter outgoing search results.  It's well known that users can search for file/album names to circumvent search bans; filtering client side prior to sending would shut that down.

This might also be used to filter during file scanning.  That covers everything.

**Comment by mathiascode** [comment]
> This might also be used to filter during file scanning. That covers everything.

It's not used when rescanning shares in SoulseekQt, at least not for now.

**Comment by mathiascode** [comment]
I got a response from Nir. He will be testing the new message for a few days to ensure everything is working fine. I'll wait until then.

**Comment by JurgenR** [comment]
> Some quick testing with different file name variations seems to suggest that SlskQt checks if a file path contains an exact banned phrase (case-insensitive). Essentially if banned_phrase in file_path.lower().

I did some testing today and that seems correct:

* "not (bryan adams) - something.mp3" : blocked
* "not bryan adams - something.mp3" : blocked
* "not bryan adamsky - something.mp3" : blocked
* "not bryan the adams - something.mp3" : not blocked
* "not_bryan_adams_- something.mp3" : not blocked

The message naming of `ExcludedSearchPhrases` is fine

**Comment by mathiascode** [comment]
Should be good to go. Email from Nir:

> Basically the only thing the client needs to do is make sure that search results that contain any of the strings in message 160 in either their folder or file name aren't returned to other users.
