### ISSUE TITLE
Distributed: we should become root when server sends search requests

### ISSUE THREAD

**Issue by JurgenR** [JurgenR/aioslsk#27]
When we are without parent and the server starts sending us search requests we should become the root and stop looking. I haven't actually seen this happen but one thing to try is just to never respond to `PotentialParents` requests. I believe after a timeout the server will just start sending the search requests directly to us.

It is labeled as a bug because I believe currently we don't accept any children if we are root, what will likely happen is that we try to get branch root and level from `parent` which is `None` in this case

**Comment by mathiascode** [comment]
> I haven't actually seen this happen but one thing to try is just to never respond to `PotentialParents` requests. I believe after a timeout the server will just start sending the search requests directly to us.

Another way to test this is to send several SendUploadSpeed messages with a large value to the server, until you have the highest upload speed of all users online. The potential parents system works by sending a list of candidates with a faster upload speed than you, so the server will eventually run out of candidates and start sending search requests.
