### ISSUE TITLE
local_path Not Set From download Setting

### ISSUE THREAD

**Issue by FluidicYottabyte** [JurgenR/aioslsk#326]
Hello,

I've been having a lovely time working with your library, but I've run into a potential issue. I'm attempting to execute a simple download. Based on the documentation, I built this:

```
async def run(self, username, password):
        self.settings = Settings(
            credentials=CredentialsSettings(
                username=username,
                password=password
            ),
            shares=SharesSettings(
                download=r'E:\Soulseek Downloads',
                scan_on_start=True
            )
        )
        self.client = SoulSeekClient(self.settings)
        
        await self.client.start()
        await self.client.login()
        
        transfer = await self.client.transfers.download(username, filename)
        
        print(transfer)
```

However, the printed transfer indicates that there is no local path, and indeed, the file never appears anywhere.

_Transfer(username='Nanachi', remote_path='Distributions\\1 Spotify Rips\\Video Game Soundtracks\\DELTARUNE Chapter 2 (Original Game Soundtrack)\\Toby Fox, Lena Raine - Cyber Battle (Solo).ogg', direction=TransferDirection.DOWNLOAD, local_path=None, state=QueuedState(Transfer(username='Nanachi', remote_path='Distributions\\1 Spotify Rips\\Video Game Soundtracks\\DELTARUNE Chapter 2 (Original Game Soundtrack)\\Toby Fox, Lena Raine - Cyber Battle (Solo).ogg', direction=TransferDirection.DOWNLOAD)))_

I've attempted to abort, manually change local_path, and then requeue, but as you probably already know requeueing resets local path to the settings value.

**Comment by JurgenR** [comment]
Hi, thanks for the feedback!

The `local_path` will only get set once the download begins, your transfer is still in the queued state. When calling `.download` the transfer will only be added to the queue, the library will handle requesting the file and downloading it from the peer in the background.

One very simple way to wait for the transfer to complete is to just add a loop, for example one that polls every 0.5 seconds and checks if the download is complete:

```python
async def run(self, username, password):
    ...
    
    transfer = await self.client.transfers.download(username, filename)
    
    print(transfer)

    while True:
        if transfer.is_finalized():
            print(f"transfer complete : {transfer}")
            break

        await asyncio.sleep(0.5)
```

This example is of course very simplistic. But it will wait until the transfer is in some finalized state (completed, aborted or failed). If the transfer was successful the `local_path` should be set. It's also possible to register to the `aioslsk.events.TransferProgressEvent` event, which would be useful when building a UI.

Do keep in mind that this is of course a P2P protocol and there's no guarantee that the file will be downloaded immediately or even ever start at all. If the peer you are downloading from has a lot of uploads queued it might take a while for him to finally start uploading to you, he might reject the upload altogether, he might go offline or there might be firewall issues and no connection could be made between the two.

If you have more questions feel free to ask 👍

**Comment by FluidicYottabyte** [comment]
Ah! Thank you for the help! My downloads are now working!

Your library is amazing by the way; I was preparing to dissect nicotine+ for this project but I'm happy to have found this.
