### ISSUE TITLE
Messages: Missing messages

### ISSUE THREAD

**Issue by JurgenR** [JurgenR/aioslsk#78]
Add missing messages from the following document: 

[protocol.zip](https://github.com/JurgenR/aioslsk/files/13055927/protocol.zip)

* ExactFileSearch (might be there)
* AdminMessage
* GlobalUserList (check if it works)
* TunneledMessage
* AddToPrivileged

**Comment by mathiascode** [comment]
In case you're interested, I maintain up-to-date documentation on messages, based on my findings when developing Nicotine+ the past few years. Perhaps some of it could be useful for your project: https://nicotine-plus.org/doc/SLSKPROTOCOL.html

Commit history: https://github.com/nicotine-plus/nicotine-plus/commits/master/doc/SLSKPROTOCOL.md

If you spot anything incorrect or missing compared to your findings, let me know. :)

**Comment by JurgenR** [comment]
@mathiascode interesting indeed :) . I took a quick look:

* Server Code 65: `ExactFileSearch` : The checksum is actually 5 bytes (+1 more than the size of a `uint32`). From my findings I could not get this to filled with anything else than 0's so I don't really know if it's even a checksum or something else. Checksum would make sense though if it's supposed to search for an exact file
* Server Code 55: `GetInterests` : Is not described but to me seemed like the idea for this message was dropped. It's purpose was probably to sync the interests stored on the server with that of the client. The client would request this without parameters right after login, server would respond with a list of strings containing the interests
* Server Code 50: `DeprecatedGetItemRecommendations` : Like Server Code 111 `GetItemRecommendations` but without the score

There were some messages that I have not listed:

* Server Code 130 : `ResetDistributed` : Should be easy to implement
* Server Code 33 : `SendConnectToken` : Not sure when this would be used?
* Server Code 153 : `RelatedSearches` : The response is missing for me because I did not understand it's purpose, I always wondered what this was for so it's good to know

I'm always curious about some of the meanings of the `unknown` parameters and the missing message codes. For example: for the messages containing the obfuscated ports, why is there a `uint32` in between? It indicates there is an obfuscated port, but why not use a `boolean` for that? Could the idea have been a list of ports at some point? I assume we'll never know :)

**Comment by mathiascode** [comment]
> * Server Code 65: `ExactFileSearch` : The checksum is actually 5 bytes (+1 more than the size of a `uint32`). From my findings I could not get this to filled with anything else than 0's so I don't really know if it's even a checksum or something else. Checksum would make sense though if it's supposed to search for an exact file

Could the additional byte be a boolean? Looking at the Wireshark Soulseek dissector, the client -> server message always had an extra byte compared to server -> client: https://gitlab.com/wireshark/wireshark/-/blob/d139a9706786ab68c3134ec42fb6012793656a29/epan/dissectors/packet-slsk.c#L1502-1515

> * Server Code 55: `GetInterests` : Is not described but to me seemed like the idea for this message was dropped. It's purpose was probably to sync the interests stored on the server with that of the client. The client would request this without parameters right after login, server would respond with a list of strings containing the interests
> * Server Code 50: `DeprecatedGetItemRecommendations` : Like Server Code 111 `GetItemRecommendations` but without the score

FWIW, the official names of these messages are:
- 50: SM_GET_SIMILAR_TERMS
- 55: SM_GET_MY_RECOMMENDATIONS

> * Server Code 33 : `SendConnectToken` : Not sure when this would be used?

The only related thing I found in the 2001 changelog for the original Soulseek client is this:

> * Implemented a new token-based user authentication module.

PySoulSeek's docstring from 2002 mentions this:

> Frankly I don't know what this is for. I don't use it.

The message was removed a few months later.

> I'm always curious about some of the meanings of the `unknown` parameters and the missing message codes.

Yeah, the remaining ones I haven't been able to figure out. I assume they served a purpose at some point, but remained to avoid breaking compatibility with old clients.

> For example: for the messages containing the obfuscated ports, why is there a `uint32` in between? It indicates there is an obfuscated port, but why not use a `boolean` for that? Could the idea have been a list of ports at some point? I assume we'll never know :)

I assumed it was a boolean originally, since SoulseekQt always uses 1 as the value, but the server happily accepts and transmits any value. I left it as unknown in the documentation for that reason.

**Comment by mathiascode** [comment]
Were you able to get a full response for the SM_GET_SIMILAR_TERMS (code 50) message to verify the contents? The server always seems to return an array with zero items.

**Comment by JurgenR** [comment]
Old versions would show a popup with the contents of the returned list when you entered an interest
